baseURL = 'https://filmind.hu/'
languageCode = 'hu'
title = 'Filmind'
theme = 'filmind'
sectionPagesMenu = "main"
[params]
  AuthorName = 'Zsolt Horváth'
  GitHubUser = 'Ch3F24'
  InstagramToken = 'IGQWRNeEk1b2tOWmQyLVJGOEhrUWdCX0w0TFZAERlNlVnVKNjdWMEhXRF96U0FnaTBieG1MLWpjTjVSenpQVmtNdl94ZAnlLbC1tUjNmMWxmN3NXenBHVVdRUDV6UnpLaV8xV2ZAScXZAqMVlFQkRLS3ZALcE1vdmJoblEZD'
  
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true