baseURL = 'http://filmind.thewst.net/'
languageCode = 'hu_HU'
title = 'Filmind'
theme = 'filmind'
sectionPagesMenu = "main"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
